#!/bin/bash

if [[ $# -eq 0 ]]; then
	echo "You must give the tests 'subdirectory' as first argument"
	# echo "You can give the project dependencies as next arguments"
	exit 1
fi
	
# Colors
COL_RESET='\033[0m'
COL_CYAN='\033[0;36m'
COL_ICYAN='\033[0;96m'
COL_YELL='\033[0;33m'
COL_IYELL='\033[0;93m'

# Compiler
COMPILER=clang
FLAGS=-g3

# Relative paths
ROOT_DIR=..

PROJECT_SRC=${ROOT_DIR}/src/${1}/*.c

# The values below are constant if relative paths are set correcty
#############################
# Unity sources and headers #
#############################
UNITY_DIR=unity
UNITY_SRC=${UNITY_DIR}/unity.c
UNITY_HEADER=${UNITY_DIR}/unity.h
#############################
# libft sources and headers #
#############################
LIBFT_DIR=${ROOT_DIR}/libft
LIBFT_HEADER=${LIBFT_DIR}/src/libft.h

# Compile and run tests in a row
for SOURCE in ${1}/*.c ; do
	${COMPILER} ${FLAGS} \
	${SOURCE} ${PROJECT_SRC} \
	${UNITY_SRC} -I${UNITY_HEADER} \
	-L${LIBFT_DIR} -lft -I${LIBFT_HEADER} \
	-o ${SOURCE/%.c/.out}
	echo -e ${COL_YELL}"Running ${SOURCE/%.c/.out}:"${COL_RESET}
	./${SOURCE/%.c/.out}
done
